config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'

  devise_for :users
  resources :steps_ingredients_joins
  resources :ingredients
  resources :recipe_steps
  resources :recipes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root 'recipes#index'
  root 'homepage#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, :description, presence: true
  has_many :recipe_steps
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
    @recipe_steps = RecipeStep.where(recipe_id: @recipe)
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @all_info = {}

    @recipe_steps = RecipeStep.where(recipe_id: @recipe).order(:number)

    @amounts = []
    @ingredients_name = []

    @recipe_steps.each do |step|
      @joins = StepsIngredientsJoin.where(recipe_step_id: step)
      @joins.each do |join|
        if not join.has_attribute? :amount
          next
        else
          @ingredients_name.append(Ingredient.find(join.ingredient_id)[:name])
          @amounts.append join.amount
        end
      end

      if @ingredients_name.empty? and @amounts.empty?
        next
      end

      @ingredients = []

      @ingredients_name.zip(@amounts) do |name, amount|
        @ingredients.append([name, amount])
      end

      @all_info[step.number] = @ingredients
      @amounts = []
      @ingredients = []
      @ingredients_name = []

    end
    # 2/0
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
    @recipe_steps = RecipeStep.where(recipe_id: @recipe).order(:number)
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:recipe).permit(:name, :description)
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for(recipe) do |f| %>
<% if recipe.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

	<ul>
		<% recipe.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="panel panel-default">

	<div class="panel-body">
		<div class="form-group">
			<%= f.label 'Nazwa' %>
			<%= f.text_field :name, class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= f.label 'Opis' %>
			<%= f.text_area :description, class: 'form-control' %>
		</div>

		<div class="actions">
			<%= f.submit 'Prześlij' , :class => 'btn btn-success' %>
		</div>
		<% end %>
	</div>
</div>

app/views/recipes/edit.html.erb
<%= render 'home/header' %>

<div class="container" style="padding-bottom: 1em">

	<h1>Edycja przepisu</h1>

	<%= render 'form', recipe: @recipe %>

	<h2>Kroki</h2>

	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Numer</th>
				<th>Opis</th>
				<th>Czas przygotowania</th>
				<th>Czas pieczenia</th>
				<th colspan="3">Opcje</th>
			</tr>
		</thead>

		<tbody>
			<% @recipe_steps.each do |recipe_step| %>
			<tr>
				<td><%= recipe_step.number %></td>
				<td><%= recipe_step.instructions %></td>
				<td><%= recipe_step.prep_time %></td>
				<td><%= recipe_step.cook_time %></td>
				<td><%= link_to 'Pokaż', recipe_step %></td>
				<td><%= link_to 'Edytuj', edit_recipe_step_path(recipe_step) %></td>
				<td><%= link_to 'Usuń', recipe_step, method: :delete, data: { confirm: 'Na pewno?' } %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<%= link_to 'Dodaj krok', new_recipe_step_path(:recipe => @recipe), class: 'btn btn-success' %>

	<%= link_to 'Pokaż', @recipe, class: 'btn btn-info' %>
	<%= link_to 'Wstecz', :back, class: 'btn btn-info' %>

</div>

app/views/recipes/index.html.erb
<%= render 'home/header' %>

<p id="notice">
	<%= notice %>
</p>

<div class="container" style="padding-bottom: 1em;">

	<h1 style="text-align: center">Przepisy</h1>

	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Nazwa</th>
				<th>Opis</th>
				<th colspan="3">Opcje</th>
			</tr>
		</thead>

		<tbody>
			<% @recipes.each do |recipe| %>
			<tr>
				<td><%= recipe.name %></td>
				<!--<td><%= recipe.description.first(120) %></td>-->
				<td><%= recipe.description %></td>
				<td><%= link_to 'Pokaż', recipe %></td>
				<td><%= link_to 'Edytuj', edit_recipe_path(recipe) %></td>
				<td><%= link_to 'Usuń', recipe, method: :delete, data: { confirm: 'Na pewno?' } %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<%= link_to 'Nowy przepis', new_recipe_path, class: 'btn btn-success' %>

</div>

app/views/recipes/new.html.erb
<%= render 'home/header' %>

<div class="container">

	<h1>Nowy przepis</h1>

	<%= render 'form', recipe: @recipe %>

	<%= link_to 'Wstecz', recipes_path, class: 'btn btn-info' %>

</div>

app/views/recipes/show.html.erb
<%= render 'home/header' %>

<div class="container" style="padding-bottom: 2em">
	<p id="notice">
		<%= notice %>
	</p>

	<h1 style="text-align: center"> <%= @recipe.name %>
	<br>
	</h1>
	<h4 style="text-align: center"> <%= @recipe.description %> </h4>
	<hr>
	<h2 style="text-align: center">Kroki</h2>

	<ul class="list-group" style="margin: 0; margin-bottom: 10px;">

		<% @recipe_steps.each do |recipe_step| %>
		<li class="list-group-item">
			<h3>Krok <%= recipe_step.number %></h3>
			<%= recipe_step.instructions %>
			<br>
			Czas przygotowania składników: <%= recipe_step.prep_time ? recipe_step.prep_time.to_s + " min." : "-" %>
			<br>
			Czas gotowania: <%= recipe_step.cook_time ? recipe_step.cook_time.to_s + " min." : "-" %>
			<br>
			<h4>Składniki</h4>
			<% if @all_info[recipe_step.number] == nil then
        next
        end %>
			<% @all_info[recipe_step.number].each do |ingredients| %>
			<%= ingredients.second %>g
			<%= ingredients.first %>
			<br>
			<% end %>
		</li>
		<% end %>

	</ul>

	<%= link_to 'Edytuj', edit_recipe_path(@recipe), class: 'btn btn-info' %>
	<%= link_to 'Wstecz', recipes_path, class: 'btn btn-info' %>

</div>