config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'

  devise_for :users
  resources :steps_ingredients_joins
  resources :ingredients
  resources :recipe_steps
  resources :recipes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root 'recipes#index'
  root 'homepage#index'
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :steps_ingredients_joins
  has_many :recipe_steps, through: :steps_ingredients_joins
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_for(ingredient) do |f| %>
<% if ingredient.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

	<ul>
		<% ingredient.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="panel panel-default">

	<div class="panel-body">

		<div class="form-group">
			<%= f.label 'Nazwa' %>
			<%= f.text_field :name, class: 'form-control' %>
		</div>

		<div class="actions">
			<%= f.submit 'Prześlij', class: 'btn btn-success' %>
		</div>
		<% end %>

	</div>
</div>

app/views/ingredients/edit.html.erb
<%= render 'home/header' %>

<div class="container">

	<h1>Edycja składnika</h1>

	<%= render 'form', ingredient: @ingredient %>

	<%= link_to 'Pokaż', @ingredient, class: 'btn btn-info' %>
	<%= link_to 'Wstecz', ingredients_path, class: 'btn btn-info' %>

</div>

app/views/ingredients/index.html.erb
<%= render 'home/header'%>

<p id="notice">
	<%= notice %>
</p>

<div class="container" style="padding-bottom: 1em;">

	<h1 style="text-align: center">Składniki</h1>

	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Nazwa</th>
				<th colspan="3">Opcje</th>
			</tr>
		</thead>

		<tbody>
			<% @ingredients.each do |ingredient| %>
			<tr>
				<td><%= ingredient.name %></td>
				<td><%= link_to 'Pokaż', ingredient %></td>
				<td><%= link_to 'Edytuj', edit_ingredient_path(ingredient) %></td>
				<td><%= link_to 'Usuń', ingredient, method: :delete, data: { confirm: 'Na pewno?' } %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<%= link_to 'Nowy składnik', new_ingredient_path, class: "btn btn-success" %>

</div>

app/views/ingredients/new.html.erb
<%= render 'home/header'%>

<div class="container">

	<h1>Nowy składnik</h1>

	<%= render 'form', ingredient: @ingredient %>

	<%= link_to 'Wstecz', ingredients_path, class: 'btn btn-info' %>

</div>

app/views/ingredients/show.html.erb
<%= render 'home/header'%>

<p id="notice">
	<%= notice %>
</p>

<div class="container">

	<strong>Nazwa:</strong>
	<%= @ingredient.name %>
	<br>

	<%= link_to 'Edytuj', edit_ingredient_path(@ingredient), class: 'btn btn-info' %>
	<%= link_to 'Wstecz', ingredients_path, class: 'btn btn-info' %>

</div>