config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'

  devise_for :users
  resources :steps_ingredients_joins
  resources :ingredients
  resources :recipe_steps
  resources :recipes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root 'recipes#index'
  root 'homepage#index'
end

app/models/steps_ingredients_join.rb
class StepsIngredientsJoin < ApplicationRecord
  belongs_to :recipe_step
  belongs_to :ingredient
end

app/controllers/steps_ingredients_joins_controller.rb
class StepsIngredientsJoinsController < ApplicationController
  before_action :set_steps_ingredients_join, only: [:show, :edit, :update, :destroy]

  # GET /steps_ingredients_joins
  # GET /steps_ingredients_joins.json
  def index
    @steps_ingredients_joins = StepsIngredientsJoin.all
  end

  # GET /steps_ingredients_joins/1
  # GET /steps_ingredients_joins/1.json
  def show
  end

  # GET /steps_ingredients_joins/new
  def new
    @steps_ingredients_join = StepsIngredientsJoin.new
    @steps_ingredients_join.recipe_step_id = params[:recipe_step_id]

    @ingredients = Ingredient.all
  end

  # GET /steps_ingredients_joins/1/edit
  def edit
  end

  # POST /steps_ingredients_joins
  # POST /steps_ingredients_joins.json
  def create
    @steps_ingredients_join = StepsIngredientsJoin.new(steps_ingredients_join_params)

    respond_to do |format|
      if @steps_ingredients_join.save
        format.html { redirect_to :back, notice: 'Steps ingredients join was successfully created.' }
        format.json { render :show, status: :created, location: @steps_ingredients_join }
      else
        format.html { render :new }
        format.json { render json: @steps_ingredients_join.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steps_ingredients_joins/1
  # PATCH/PUT /steps_ingredients_joins/1.json
  def update
    respond_to do |format|
      if @steps_ingredients_join.update(steps_ingredients_join_params)
        format.html { redirect_to @steps_ingredients_join, notice: 'Steps ingredients join was successfully updated.' }
        format.json { render :show, status: :ok, location: @steps_ingredients_join }
      else
        format.html { render :edit }
        format.json { render json: @steps_ingredients_join.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps_ingredients_joins/1
  # DELETE /steps_ingredients_joins/1.json
  def destroy
    @steps_ingredients_join.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Steps ingredients join was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_steps_ingredients_join
      @steps_ingredients_join = StepsIngredientsJoin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def steps_ingredients_join_params
      params.require(:steps_ingredients_join).permit(:recipe_step_id, :ingredient_id, :amount)
    end
end

app/helpers/steps_ingredients_joins_helper.rb
module StepsIngredientsJoinsHelper
end

app/views/steps_ingredients_joins/_form.html.erb
<%= form_for(steps_ingredients_join) do |f| %>
<% if steps_ingredients_join.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(steps_ingredients_join.errors.count, "error") %> prohibited this steps_ingredients_join from
	being saved:</h2>

	<ul>
		<% steps_ingredients_join.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="form-group">
	<%= f.label :recipe_step_id %>
	<%= f.text_field :recipe_step_id, readonly: true, class: 'form-control' %>
</div>

<div class="form-group">
	<%= f.label :ingredient_id %>
	<%= f.collection_select :ingredient_id, Ingredient.order(:name), :id, :name, {include_blank: false}, {class: "form-control"} %>
</div>

<div class="form-group">
	<%= f.label :amount %>
	<%= f.number_field :amount, class: 'form-control' %>
</div>

<div class="actions">
	<%= f.submit 'Dodaj składnik do kroku', class: 'btn btn-success' %>
</div>
<% end %>

app/views/steps_ingredients_joins/edit.html.erb
<h1>Editing Steps Ingredients Join</h1>

<%= render 'form', steps_ingredients_join: @steps_ingredients_join %>

<%= link_to 'Show', @steps_ingredients_join %> |
<%= link_to 'Back', steps_ingredients_joins_path %>

app/views/steps_ingredients_joins/index.html.erb
<%= render 'home/header' %>

<div class="container">

	<p id="notice">
		<%= notice %>
	</p>

	<h1>Steps Ingredients Joins</h1>

	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Recipe step</th>
				<th>Ingredient</th>
				<th>Amount</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @steps_ingredients_joins.each do |steps_ingredients_join| %>
			<tr>
				<td><%= steps_ingredients_join.recipe_step.id %></td>
				<td><%= steps_ingredients_join.ingredient.id %></td>
				<td><%= steps_ingredients_join.amount %></td>
				<td><%= link_to 'Show', steps_ingredients_join %></td>
				<td><%= link_to 'Edit', edit_steps_ingredients_join_path(steps_ingredients_join) %></td>
				<td><%= link_to 'Destroy', steps_ingredients_join, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<br>

	<%= link_to 'New Steps Ingredients Join', new_steps_ingredients_join_path %> |
	<%= link_to 'Recipes', recipes_path %> |
	<%= link_to 'Ingredients', ingredients_path %>

</div>

app/views/steps_ingredients_joins/new.html.erb
<%= render 'home/header' %>

<div class="container">

	<h1>Nowy składnik do kroku</h1>

	<%= render 'form', steps_ingredients_join: @steps_ingredients_join %>

	<%= link_to 'Wstecz', recipe_step_path(@steps_ingredients_join.recipe_step_id), class: 'btn btn-info' %>

</div>

app/views/steps_ingredients_joins/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<p>
	<strong>Recipe step:</strong>
	<%= @steps_ingredients_join.recipe_step %>
</p>

<p>
	<strong>Ingredient:</strong>
	<%= @steps_ingredients_join.ingredient %>
</p>

<p>
	<strong>Amount:</strong>
	<%= @steps_ingredients_join.amount %>
</p>

<%= link_to 'Edit', edit_steps_ingredients_join_path(@steps_ingredients_join) %> |
<%= link_to 'Back', steps_ingredients_joins_path %>